@echo off
cd /d "%~dp0"
echo Uruchamianie Sanguivia...
echo Sprawdzanie electron...
dir node_modules\electron\dist\electron.exe
echo Uruchamianie electron...
node_modules\electron\dist\electron.exe build\electron.js
pause